# Generated by Django 2.0.4 on 2018-11-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_grp', models.CharField(max_length=3)),
                ('med_hist', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
                ('view_perm', models.BooleanField()),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_core.HealthProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PreConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('specialization', models.CharField(max_length=30)),
            ],
        ),
    ]
