# Generated by Django 2.1.1 on 2018-11-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('exc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('day', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserModel')),
            ],
        ),
        migrations.AddField(
            model_name='routines',
            name='schd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.Schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user', 'day')},
        ),
    ]
