# Generated by Django 2.1.1 on 2018-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Monday', max_length=15),
        ),
    ]
