# Generated by Django 2.1.1 on 2018-11-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20181121_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
