# Generated by Django 2.1.1 on 2018-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_remove_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
