# Generated by Django 2.1.2 on 2018-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsessiontoken',
            name='session_token',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersessiontoken',
            name='session_token',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
