# Generated by Django 2.1.2 on 2018-11-01 14:09

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20181101_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='auth_document',
            field=models.FileField(default='', upload_to='authenticationDocs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='auth_document_url',
            field=models.CharField(default='abc.file', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='degree',
            field=models.CharField(default='B', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='experience',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='specialization',
            field=models.CharField(default='sasa', max_length=255),
            preserve_default=False,
        ),
    ]
