# Generated by Django 2.1.2 on 2018-11-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20181101_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='dateOfBirth',
            field=models.DateTimeField(),
        ),
    ]
