# Generated by Django 2.1.2 on 2018-11-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20181101_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSessionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.DoctorModel')),
            ],
        ),
        migrations.RenameModel(
            old_name='SessionToken',
            new_name='UserSessionToken',
        ),
    ]
