# Generated by Django 2.0.4 on 2018-11-10 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.DoctorModel'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='no_days',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserModel'),
        ),
    ]
