# Generated by Django 2.0.4 on 2018-11-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_core', '0002_auto_20181106_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
